[workspace]
members = [
    "lib", 
    "."
]

[package]
name = "doc-assert-bin"
version = "0.1.0"
edition = "2021"
description = "A tool to assert the output of a markdown file against a remote source"

[dependencies]
doc-assert = { path = "./lib" }
clap = { version = "4.4.18", features = ["derive"]}
tokio = { version = "1.35.1", features = ["full"] }

[[bin]]
name = "doc-assert"
path = "src/main.rs"


# [lib]
# name = "doc_assert"

# [features]
# build-binary = ["clap"]

# [[bin]]
# name = "doc-assert"
# path = "src/main.rs"
# required-features = ["build-binary"]

# [package]
# name = "doc-assert"
# version = "0.1.0"
# edition = "2021"

# [dependencies]
# markdown = "1.0.0-alpha.16"
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
# reqwest = { version = "0.11.24", features = ["json"] }
# tokio = { version = "1.35.1", features = ["full"] }
# mockito = "1.2.0"
# clap = { version = "4.4.18", features = ["derive"] }