name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: lint, build & test
    runs-on: ubuntu-latest
    steps:
    - uses: actions-rs/cargo@v1
    - name: Format
      run: cargo --all -- --check
    - name: Lint
      run: cargo clippy # add `-- -D warnings` when ready
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
